json.start @summary.start
json.stop @summary.stop
json.driving_distance @summary.distance
json.driving_time @summary.time
json.total_gallons @summary.gallons_needed
json.price_per_gallon @summary.gas_price
json.driving_cost @summary.total_cost
json.flight_itinerary @summary.itinerary
json.flight_cost @summary.price
